### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by jillianw**

### CODE REVIEW

**Comment by jillianw** [comment]
I know that this code works:

def format_phone_number(phone_number_str)
  b = phone_number_str
  b = "(" + b[0..2] + ")" + " " + b[3..5] + "-" + b[6..9]
end

...because I tried it in repl.it (with phone_number_str = "4025555555" at the beginning) and it gave me what I was looking for. But... I'm getting errors. Am I just approaching this the wrong way?

**Comment by sumeetjain** [comment]
Is this question still relevant? Not sure if our most recent chat moved you in another direction or not.

If the question is still relevant, please try to tell me more about what you're expecting/desiring will happen versus what actually happens?

**Comment by jillianw** [comment]
Our conversation took care of it. :)

**Comment by sumeetjain** [comment]
Is this still a WIP?

**Comment by sumeetjain** [comment]
Is this still a WIP, or should I look at it to check completion?

**Comment by jillianw** [comment]
No, it's done! I didn't know if we were able to change what we put in the quotes after git commit -m? During the prep work I was under the impression it hadn't to stay constant.

Thanks!

**Comment by sumeetjain** [comment]
Gotcha–my bad for not explaining that. You can write any message for each commit.

**Comment by sumeetjain** [comment]
:+1:

**Pull request closed without merging**
